// Firebase Configuration
// Firebase configuration is done via FlutterFire CLI
// Run: flutter pub global activate flutterfire_cli
// Then: flutterfire configure
// Select Web platform only
// This will generate lib/firebase_options.dart automatically

class FirebaseConfig {
  // No manual configuration needed
  // The firebase_options.dart file is generated by flutterfire configure
  // Make sure to select Web platform when running flutterfire configure
}

